### ISSUE TITLE
upstream version 2.3.9 released

### ISSUE THREAD

**Issue by ZyanKLee** [asciiprod/yadifa#10]
upstream has released source package 2.3.9
would you please upgrade the debian package to the new version?

thanks a lot for your great work!

**Comment by asciiprod** [comment]
Sure, already done. But I am no Debian developer/maintainer. So it will depend on the goodwill of a sponsor when/if it will end up in Debian. Feel free to pull and build from the repo

**Comment by ZyanKLee** [comment]
Thank you asciiprod,

I'm working on a docker image that would be pushed to the public hub. For
that I use your work as a basis. If you are interested, I'll keep you
posted on news regarding that work?

>
