### ISSUE TITLE
Absolute paths not correctly interpreted

### ISSUE THREAD

**Issue by ghost** [asciiprod/yadifa#9]
**Version:** yadifa 2.2.3-6237 (2016-11-30)

```
<zone>
	domain		domain.eu.
	file 		/etc/yadifa/zones/domain.eu.zone
	type		master
</zone>
```

`zone load: 'domain.eu.' could not open file '/var/lib/yadifa//etc/yadifa/zones/domain.eu.zone': No such file or directory ( 0.000018s)`

**Comment by asciiprod** [comment]
See man page: The zone file is relative to 'datapath' (mandatory for a master)
If you feel this should work, please contact upstream authors from EUrid
https://www.yadifa.eu/mailing-list-users

I just do the packaging for Debian.
